### PR TITLE
Fix labeller issue where no image was loaded

### LINKED ISSUE #184: Unable to retrieve images in labeller
**Describe the bug**
Clicking on __Edit__ on an image opens up to a blank screen.

**To Reproduce**
1. Go to existing project
2. Add a label (Bounding Box)
3. Add an image
3. Click on __Edit__ for the image

**Expected behavior**
Clicking on __Edit__ for the image should open up the labeller.

**Screenshots**
labeller_1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79

**Additional context**
I was able to fix this issue by changing `imageUrl` in the labeller component.

### PR DESCRIPTION
**Pull request by laksh22**
# Description
Clicking on __Edit__ on an image opened up to a blank screen. The image URL has been changed to make sure that the labeller opens up properly.

Fixes #184  (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

3 images and 4 labels were added, after which __Edit__ button was clicked for each image which opened up the labeller properly.

**Test Configuration**:
labeller_2

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: labellab-client/src/components/labeller/index.js [hunk 1]
```diff
@@ -115,7 +115,9 @@ class LabelingLoader extends Component {
             labels={lab}
             labelData={(img && img.labelData) || {}}
             imageUrl={
+              'http://' +
```
Comment (Tushar19varshney) [inline labellab-client/src/components/labeller/index.js]: It could be either http/https when it will be production stage. So, it's better to include that in HOST variable.

Comment (laksh22) [reply labellab-client/src/components/labeller/index.js]: @Tushar19varshney Sure, that makes sense. `FetchAPI.js` contains the following code:
```
if (process.env.REACT_APP_SERVER_ENVIORNMENT === 'dev') {
    url =
      'http://' +
      process.env.REACT_APP_HOST +
      ':' +
      process.env.REACT_APP_SERVER_PORT +
      url
  }
```
and `project/images.js` also adds `http://` to `process.env.REACT_APP_HOST`. Should I make the necessary changes to these files instead, so that we can keep `REACT_APP_HOST=http://localhost:` during development?

Comment (Tushar19varshney) [reply labellab-client/src/components/labeller/index.js]: Yes and also add the instructions in the `README.md` so that it will be easy for other developers to understand.
