### PR TITLE
Fix label delete issue

### LINKED ISSUE #323: Label deletion fails in the mobile app
**Describe the bug**
Lable delete function doesn't work in the mobile application. 

**To Reproduce**
1. Go to a project
2. Add a new label
3. Select label to go to label options
4. Delete it

**Expected behavior**
The label should be deleted correctly when the label delete function is triggered. 

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10

**Additional context**
I would like to work on this fix. I think the fault is in the delete request. Client sents the label id attribute as a parameter but the server expects the original id of the label ( _id attribute )

### PR DESCRIPTION
**Pull request by cazci**
# Description

Fix the label delete request with replacing label id with label _id. 

Fixes #323 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: labellab_mobile/lib/model/label.dart [hunk 1]
```diff
@@ -7,17 +7,20 @@ class Label {
   String id;
   String name;
   String type;
+  String mongoId;
```
Comment (UdeshUK) [inline labellab_mobile/lib/model/label.dart]: Can you replace mongo reference here? Variable of the client doesn't have to depict backends technologies. Refactor to a neutral name.

Comment (cazci) [reply labellab_mobile/lib/model/label.dart]: Noted :+1: Thank you.
